### ISSUE TITLE
Issue with Random

### ISSUE THREAD

**Issue by DinasEmrys** [Arraying/Arraybot#20]
currently attempting to make a custom command with a randomized value, however, the 1;2;3 system mentioned on the wiki isn't working and the {random} value mentioned in one of the answers in the issues isn't either.

For example:
Dinas: //custom setvalue test 1;2;3;4;5
BOTArraybot: The custom command has been updated.
Dinas://test
BOTArraybot: 1;2;3;4;5

**Comment by xJade00** [comment]
Wiki is outdated for now. It's being worked on slowly. `//custom setvalue test 1;2;3;4;5 --random` is what you want.
